import { rgba } from "polished";
import { breakpoints } from "./breakpoints";

const defaultColors = {
  primary: "#473bf0",
  primaryHover: "#1c10cf",
  secondary: "#f64b4b",
  light: "#ffffff",
  dark: "#161c2d",
  yellow: "#fedc5a",
  ash: "#413e65",
  green: "#68d585 ",
  info: "#0e567c",
};

const colors = {
  primary: defaultColors.primary,
  primaryHover: defaultColors.primaryHover,
  secondary: defaultColors.secondary,
  light: defaultColors.light,
  lightShade: rgba(255,255,255, 1),
  dark: defaultColors.dark,
  darkShade: rgba(255,255,255, 1),
  ash: defaultColors.ash,
  bg: defaultColors.light,
  bg2: "#ffffff",
  bg3: "#ffffff",
  bg4: "#ffffff",
  bg5: "#ffffff",
  bg6: "#ffffff",
  bg7: "#ffffff",
  border: "#ffffff",
  shadow: rgba(defaultColors.dark, 0.15),
  heading: defaultColors.dark,
  text: rgba(255,255,255, 1),
  warning: defaultColors.yellow,
  success: defaultColors.green,
  info: defaultColors.info,

  modes: {
    dark: {
      primary: defaultColors.primary,
      primaryHover: defaultColors.primaryHover,
      secondary: defaultColors.secondary,
      light: defaultColors.light,
      lightShade: rgba(255,255,255, 1),
      dark: defaultColors.dark,
      darkShade: rgba(255,255,255, 1),
      ash: defaultColors.ash,
      bg: defaultColors.light,
      bg2: "#ffffff",
      bg3: "#ffffff",
      bg4: "#ffffff",
      bg5: "#ffffff",
      bg6: "#ffffff",
      bg7: "#ffffff",
      border: "#ffffff",
      shadow: rgba(defaultColors.dark, 0.15),
      heading: defaultColors.dark,
      text: rgba(255,255,255, 1),
      warning: defaultColors.yellow,
      success: defaultColors.green,
      info: defaultColors.info,
    },
  },
};

const theme = {
  initialColorModeName: "light",
  colors: colors,
  space: [
    0,
    4,
    8,
    12,
    16,
    20,
    24,
    28,
    32,
    36,
    40,
    48,
    52,
    56,
    60,
    64,
    72,
    84,
    100,
    120,
    140,
  ],
  breakpoints: [
    `${breakpoints.sm}px`,
    `${breakpoints.md}px`,
    `${breakpoints.lg}px`,
    `${breakpoints.xl}px`,
  ],
};

export default theme;
